server:
  port: 8082
spring:
  application:
    name: images-api
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-200-5-135.compute-1.amazonaws.com:5432/dee5c43sgovkb3?sslmode=disable
    username: zxaudipbwbrgsb
    password: 4a97db46e70d295aa3a82756eee3628e4a8a379220aa7c3d5dbfbf013114f3db
  jpa:
    generate-ddl: 'false'
    database: POSTGRESQL
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
          lob:
            non_contextual_creation: 'true'
      org:
        hibernate:
          flushMode: COMMIT
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      continue-on-error: 'false'
      platform: postgresql

qr:
  code:
    width: 200
    height: 200

